server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/VictoriaBorquez/microservicios-java
          search-paths: config-data
  application:
    name: pep3-config-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/listaproductos?useSSL=false&serverTimezone=UTC
    username: sprinboot
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
  